Repository volcengine/verl, pull requests merged in 2025-05, with the labels that each got.

#1026 [fsdp] feat: support fsdp2 training and inference in fsdp_workers
  docs/experiment/ppo.rst
  tests/checkpoint/test_fsdp_ckpt.py
  verl/trainer/config/ppo_trainer.yaml
  verl/trainer/main_ppo.py
  verl/utils/checkpoint/fsdp_checkpoint_manager.py
  verl/utils/fsdp_utils.py
  verl/workers/actor/dp_actor.py
  verl/workers/critic/dp_critic.py
  verl/workers/fsdp_workers.py
  verl/workers/sharding_manager/fsdp_sglang.py
  verl/workers/sharding_manager/fsdp_vllm.py
Labels: fsdp, status: review in process

#1356 [feat] Add auto padding for DataProto
  tests/ray/test_auto_padding.py
  verl/protocol.py
  verl/single_controller/base/decorator.py
  verl/single_controller/base/worker.py
  verl/single_controller/ray/base.py
Labels: status: need review

#1282 [trainer] breaking: pass dataset as required args to SFTTrainer; also change ppo ray trainer to take custom datasets as inputs
  recipe/prime/prime_ray_trainer.py
  tests/e2e/sft/test_sp_loss_match.py
  verl/trainer/fsdp_sft_trainer.py
  verl/trainer/main_ppo.py
  verl/trainer/ppo/ray_trainer.py
  verl/utils/dataset/rl_dataset.py
Labels: status: need review

#1372 [ci][fix] Enable part of ray test to be run on CPU machine
  .github/workflows/ray_cpu_test.yml
  .github/workflows/ray_gpu_test.yml
  tests/ray_cpu/check_worker_alive/main.py
  tests/ray_cpu/test_auto_padding.py
  tests/ray_cpu/test_check_worker_alive.py
  tests/ray_cpu/test_decorator.py
  tests/ray_cpu/test_fused_workers.py
  tests/ray_cpu/test_ray_local_envs.py
  tests/ray_gpu/detached_worker/README.md
  tests/ray_gpu/detached_worker/client.py
  tests/ray_gpu/detached_worker/run.sh
  tests/ray_gpu/detached_worker/server.py
  tests/ray_gpu/test_colocated_workers.py
  tests/ray_gpu/test_colocated_workers_fused.py
  tests/ray_gpu/test_data_transfer.py
  tests/ray_gpu/test_driverfunc_to_worker.py
  tests/ray_gpu/test_high_level_scheduling_api.py
  tests/ray_gpu/test_rvdz.py
  tests/ray_gpu/test_worker_group_basics.py
  tests/ray_gpu/test_worker_group_torch.py
  verl/single_controller/base/worker.py
Labels: status: accepted

#1378 [fix][ci] fix two pipelines that fails on the main branch
  .github/workflows/dataset.yml
  .github/workflows/ray_cpu_test.yml
Labels: status: need review

#1297 [rollout] misc: add demo chat completion scheduler described in ReTool paper
  examples/ppo_trainer/naive_chat_scheduler.py
  tests/rollout/async_rollout_utils.py
  tests/rollout/test_vllm_multi_turn.py
  tests/rollout/test_vllm_tool_calling.py
  verl/workers/rollout/async_server.py
  verl/workers/rollout/vllm_rollout/vllm_async_server.py
Labels: status: need review

#1267 Qwen2moe[part1]: add cpu converter option, add CI test for current solutions temporarily
  .github/workflows/checkpoint_converter.yml
  .github/workflows/e2e_ppo_trainer_megatron.yml
  docs/advance/checkpoint.rst
  docs/workers/megatron_workers.rst
  scripts/converter_hf_to_mcore.py
  verl/utils/megatron_utils.py
  verl/utils/model.py
Labels: status: need review

#1424 [single_controller][decorator] Define a `DynamicEnum` class to make `Dispatch` and `Execute` extensible.
  tests/verl/test_decorator.py
  verl/single_controller/base/decorator.py
  verl/utils/py_functional.py
Labels: status: accepted

#1423 [rollout] fix: missing trust_remote_code option in rollout initialization
  docs/examples/config.rst
  verl/trainer/config/ppo_trainer.yaml
  verl/workers/fsdp_workers.py
  verl/workers/rollout/sglang_rollout/async_sglang_rollout.py
  verl/workers/rollout/sglang_rollout/sglang_rollout.py
Labels: status: accepted

#1390 [docs] refactor: use verl consistently in the codebase
  .github/workflows/sanity.yml
  docker/Dockerfile.vemlp.vllm.te
  docs/README_vllm0.7.md
  verl/workers/megatron_workers.py
Labels: status: need review

#1401 [vllm rollout] minor fix: make vllm version determination stronger
  requirements.txt
  setup.py
  verl/workers/rollout/vllm_rollout/__init__.py
Labels: status: review in process, status: accepted

#1392 [tests] BREAKING: move recipe.dapo.src to recipe.dapo; move test files to their own namespaces (tests/verl/xxx -> tests/xxx)
  .github/workflows/dataset.yml
  .github/workflows/model.yml
  .github/workflows/sgl.yml
  .github/workflows/verl_unit_test.yml
  .github/workflows/vllm.yml
  .gitignore
  docs/api/trainer.rst
  docs/perf/perf_tuning.rst
  recipe/dapo/config/dapo_trainer.yaml
  recipe/dapo/dapo_ray_trainer.py
  recipe/dapo/main_dapo.py
  recipe/dapo/run_dapo_early_qwen2.5_32b.sh
  recipe/dapo/run_dapo_qwen2.5_32b.sh
  recipe/dapo/run_dapo_wo_ds_qwen2.5_32b.sh
  recipe/dapo/test_dapo_7b.sh
  tests/e2e/generation/run_gen_qwen05.sh
  tests/e2e/run_dapo.sh
  tests/models/test_transformer.py
  tests/models/test_transformers_ulysses.py
  tests/single_controller/base/test_decorator.py
  tests/test_protocol.py
  tests/utility/test_timeout_decorator.py
  tests/utils/checkpoint/test_fsdp_ckpt.py
  tests/utils/dataset/test_multiturn_sft_dataset.py
  tests/utils/dataset/test_rl_dataset.py
  tests/utils/dataset/test_rm_dataset.py
  tests/utils/dataset/test_sft_dataset.py
  tests/utils/test_flops_counter.py
  tests/utils/test_import_utils.py
  tests/utils/test_model.py
  tests/utils/test_module.py
  tests/workers/rollout/async_rollout_utils.py
  tests/workers/rollout/run_fsdp_vllm.py
  tests/workers/rollout/test_hf_rollout.py
  tests/workers/rollout/test_sglang_async_rollout_w_tools.py
  tests/workers/rollout/test_sglang_async_spmd.py
  tests/workers/rollout/test_sglang_spmd.py
  tests/workers/rollout/test_vllm_hf_loader.py
  tests/workers/rollout/test_vllm_multi_turn.py
  tests/workers/rollout/test_vllm_spmd.py
  tests/workers/rollout/test_vllm_tool_calling.py
  tests/workers/rollout/utils_sglang.py
  verl/single_controller/base/worker.py
  verl/utils/megatron_utils.py
  verl/utils/reward_score/math_dapo.py
  verl/utils/reward_score/prime_math/__init__.py
  verl/utils/reward_score/prime_math/grader.py
  verl/workers/megatron_workers.py
  verl/workers/sharding_manager/megatron_sglang.py
Labels: status: accepted

#1440 [BUG] fix value mask bug in dp_critic
  verl/workers/critic/dp_critic.py
Labels: status: accepted

#1470 [refactor][single_controller] Small refactor and fixes in `worker.py` and `ray.base.py`
  verl/single_controller/base/worker.py
  verl/single_controller/ray/base.py
Labels: status: need review

#1509 [fix][DataProto] Make classmethod `from_single_dict` return a cls not the class name
  tests/test_protocol.py
  verl/protocol.py
Labels: status: need review

#1400 [lr_schedular] fix: implement proper min_lr_ratio support in cosine scheduler
  docs/examples/config.rst
  verl/trainer/config/ppo_trainer.yaml
  verl/utils/torch_functional.py
  verl/workers/fsdp_workers.py
Labels: status: accepted

#1429 [feat] Sandbox: support sandbox fusion on FaaS & localhost
  docs/examples/sandbox_fusion_example.rst
  examples/ppo_trainer/run_deepseek7b_llm_sandbox_fusion.sh
  tests/reward_score/test_sandbox_fusion.py
  tests/sandbox/test_sandbox.py
  verl/trainer/config/ppo_megatron_trainer.yaml
  verl/trainer/config/ppo_trainer.yaml
  verl/trainer/ppo/reward.py
  verl/utils/reward_score/__init__.py
  verl/utils/reward_score/prime_code/__init__.py
  verl/utils/reward_score/sandbox_fusion/__init__.py
  verl/utils/reward_score/sandbox_fusion/utils.py
Labels: status: need review

#1290 clean utils code.
  verl/utils/reward_score/prime_code/testing_util.py
  verl/utils/torch_functional.py
Labels: status: accepted

#1444 [megatron] Qwen3moe-part 2: Allow Infer and train tp to be different with CI tests, Fix vllm resharding process
  .github/workflows/e2e_ppo_trainer_megatron.yml
  docs/workers/megatron_workers.rst
  examples/grpo_trainer/run_qwen2_5-7b_math_megatron_diff_tp.sh
  tests/e2e/run_ppo_trainer_megatron.sh
  verl/models/mcore/config_converter.py
  verl/workers/megatron_workers.py
  verl/workers/sharding_manager/megatron_vllm.py
Labels: status: need review, high priority

#1396 [doc] [1/N] Adding doc strings and doc pages for public methods in `single_controller`
  .github/workflows/doc.yml
  docs/api/data.rst
  docs/api/single_controller.rst
  docs/index.rst
  docs/start/install.rst
  docs/workers/sglang_worker.rst
  verl/single_controller/base/decorator.py
  verl/single_controller/base/worker.py
  verl/single_controller/base/worker_group.py
  verl/single_controller/ray/base.py
  verl/single_controller/ray/megatron.py
Labels: status: review in process

#1442 add `engine_kwargs` in vllm_rollout_spmd to set params in vllm engine
  verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
Labels: status: accepted

#1555 [Megatron][BREAKING] Allow override of transformer config to enable custom megatron features like variable PP layers distribution, with CI tests
  .github/workflows/e2e_ppo_trainer_megatron.yml
  .vscode/settings.json
  scripts/model_merger.py
  tests/e2e/run_ppo_trainer_megatron.sh
  tests/e2e/run_prime.sh
  verl/models/mcore/config_converter.py
  verl/models/mcore/registry.py
  verl/single_controller/base/megatron/worker.py
  verl/trainer/config/ppo_megatron_trainer.yaml
  verl/utils/megatron_utils.py
  verl/utils/model.py
  verl/workers/megatron_workers.py
  verl/workers/sharding_manager/megatron_vllm.py
Labels: status: review in process

#1407 [New Recipe] SPIN algorithm implementation
  .github/workflows/e2e_spin.yml
  docs/experiment/ppo.rst
  recipe/spin/README.md
  recipe/spin/config/spin_trainer.yaml
  recipe/spin/core_algos.py
  recipe/spin/dp_actor.py
  recipe/spin/fsdp_workers.py
  recipe/spin/main_spin.py
  recipe/spin/run_spin.sh
  recipe/spin/spin_trainer.py
  tests/e2e/run_spin.sh
Labels: status: need review

#1220 Activation Offloading
  docs/examples/config.rst
  docs/perf/perf_tuning.rst
  tests/utils/gpu_tests/test_activation_offload.py
  verl/trainer/config/ppo_trainer.yaml
  verl/utils/activation_offload.py
  verl/workers/fsdp_workers.py
Labels: status: review in process

#1397 [doc][2/N] Adding doc strings and doc pages for public methods in `trainer` and `utils`
  docs/api/single_controller.rst
  docs/api/trainer.rst
  docs/api/utils.rst
  docs/conf.py
  docs/index.rst
  tests/ray_cpu/test_ray_utils.py
  tests/sandbox/test_sandbox.py
  tests/utils/gpu_tests/megatron/test_pipeline_parallel.py
  verl/trainer/ppo/core_algos.py
  verl/trainer/ppo/ray_trainer.py
  verl/trainer/ppo/reward.py
  verl/utils/checkpoint/checkpoint_manager.py
  verl/utils/checkpoint/fsdp_checkpoint_manager.py
  verl/utils/dataset/rl_dataset.py
  verl/utils/debug/performance.py
  verl/utils/fs.py
  verl/utils/megatron/pipeline_parallel.py
  verl/utils/megatron/sequence_parallel.py
  verl/utils/py_functional.py
  verl/utils/ray_utils.py
  verl/utils/reward_score/__init__.py
  verl/utils/seqlen_balancing.py
  verl/utils/torch_functional.py
  verl/utils/tracking.py
  verl/utils/ulysses.py
  verl/workers/reward_manager/dapo.py
  verl/workers/reward_manager/naive.py
  verl/workers/reward_manager/prime.py
Labels: status: need review

#1284 [mcore] moonlight (small model with deepseekv3 arch)
  examples/ppo_trainer/run_moonlight16b_a3b_gsm8k_megatron.sh
  scripts/converter_hf_to_mcore.py
  verl/models/mcore/config_converter.py
  verl/models/mcore/model_initializer.py
  verl/models/mcore/patch_v012.py
  verl/models/mcore/registry.py
  verl/models/mcore/saver.py
  verl/models/mcore/weight_converter.py
  verl/models/weight_loader_registry.py
  verl/single_controller/base/megatron/worker.py
  verl/trainer/config/ppo_megatron_trainer.yaml
  verl/utils/megatron_utils.py
  verl/workers/megatron_workers.py
Labels: status: review in process

#1639 [feat] support kimi_vl VLM model
  verl/models/transformers/kimi_vl.py
  verl/models/transformers/monkey_patch.py
  verl/trainer/main_ppo.py
  verl/utils/vllm_utils.py
  verl/workers/fsdp_workers.py
  verl/workers/rollout/vllm_rollout/vllm_rollout_spmd.py
  verl/workers/sharding_manager/fsdp_vllm.py
Labels: status: need review

#1682 [sglang] Feat: Search Tool Invocation in Multi-Turn RL Training
  .github/workflows/sgl.yml
  docs/sglang_multiturn/multiturn.rst
  docs/sglang_multiturn/search_tool_example.rst
  examples/data_preprocess/preprocess_search_r1_dataset.py
  examples/sft/gsm8k/run_qwen_05_peft.sh
  examples/sft/gsm8k/run_qwen_05_sp2.sh
  examples/sft/gsm8k/run_qwen_05_sp2_liger.sh
  examples/sft/multiturn/run_qwen_05_sp2.sh
  examples/sglang_multiturn/config/search_multiturn_grpo.yaml
  examples/sglang_multiturn/config/tool_config/search_tool_config.yaml
  examples/sglang_multiturn/search_r1_like/local_dense_retriever/download.py
  examples/sglang_multiturn/search_r1_like/local_dense_retriever/retrieval_server.py
  examples/sglang_multiturn/search_r1_like/run_qwen2.5-3b_instruct_search_multiturn.sh
  requirements_sglang.txt
  tests/workers/rollout/resource/tool_configs/search_tool_config
  tests/workers/rollout/test_sglang_async_rollout_search_tools.py
  verl/tools/search_tool.py
  verl/tools/utils/__init__.py
  verl/tools/utils/search_r1_like_utils.py
  verl/utils/reward_score/__init__.py
  verl/utils/reward_score/search_r1_like_qa_em.py
Labels: status: need review
