Repository volcengine/verl, pull requests merged in 2025-06, with the labels that each got.

#1465 [Feat] Add support for RAY_EXPERIMENTAL_NOSET_*_VISIBLE_DEVICES (Fix AMD support)
  docker/Dockerfile.rocm
  docs/amd_tutorial/amd_build_dockerfile_page.rst
  verl/single_controller/base/worker.py
  verl/utils/ray_utils.py
  verl/workers/actor/megatron_actor.py
  verl/workers/critic/megatron_critic.py
Labels: AMD

#1701 [feat][BREAKING] Megatron: Support learning rate scheduler
  .github/workflows/e2e_ppo_trainer_megatron.yml
  docs/examples/config.rst
  tests/e2e/run_ppo_trainer_megatron.sh
  verl/trainer/config/ppo_megatron_trainer.yaml
  verl/utils/checkpoint/megatron_checkpoint_manager.py
  verl/utils/megatron/optimizer.py
  verl/utils/megatron_utils.py
  verl/workers/actor/megatron_actor.py
  verl/workers/megatron_workers.py
Labels: status: need review

#1820 [perf] feat: Add verl profiling support from Nvidia Nsight System
  docker/Dockerfile.vllm.sglang.megatron
  docs/index.rst
  docs/perf/nsight_profiling.md
  examples/ppo_trainer/run_deepseek_math_gsm8k_megatron_nsys.sh
  examples/ppo_trainer/run_qwen2-7b_rm_seq_balance_nsys.sh
  recipe/dapo/dapo_ray_trainer.py
  recipe/dapo/main_dapo.py
  recipe/prime/prime_ray_trainer.py
  recipe/sppo/sppo_ray_trainer.py
  verl/single_controller/ray/base.py
  verl/trainer/config/ppo_megatron_trainer.yaml
  verl/trainer/config/ppo_trainer.yaml
  verl/trainer/main_ppo.py
  verl/trainer/ppo/ray_trainer.py
  verl/utils/debug/__init__.py
  verl/utils/debug/empty_annotations.py
  verl/utils/debug/nvtx_profile.py
  verl/utils/debug/performance.py
  verl/utils/debug/profile.py
  verl/utils/import_utils.py
  verl/workers/fsdp_workers.py
  verl/workers/megatron_workers.py
  verl/workers/sharding_manager/fsdp_sglang.py
  verl/workers/sharding_manager/fsdp_vllm.py
  verl/workers/sharding_manager/megatron_sglang.py
  verl/workers/sharding_manager/megatron_vllm.py
Labels: status: review in process
